# OpenAI Configuration
openai:
  embedding_model: "text-embedding-ada-002"
  model: "gpt-4o-mini"
  api_key: "9c77b8857fcc4df89e980c45ba0f4daa"
  base_url: "https://api.aimlapi.com/v1"

# GLM Configuration
glm:
  model: "glm-4-plus"
  api_key: "***"
  base_url: "https://open.bigmodel.cn/api/paas/v4"
  embedding_model: "embedding-3"

# Deepseek Configuration
deepseek:
  model: "deepseek-chat"
  api_key: "***"
  base_url: "https://api.deepseek.com"

# Model Parameters
model_params:
  openai_embedding_dim: 1536
  glm_embedding_dim: 2048
  max_token_size: 8192

# HiRAG Configuration
hirag:
  working_dir: "test"
  enable_llm_cache: true
  enable_hierachical_mode: true
  embedding_batch_num: 6
  embedding_func_max_async: 8
  enable_naive_rag: true